2020-10-29 16:07:18,329 INFO: SQLAlchemy startup [in /home/marc/programming/sqlalchemy_app/app/__init__.py:29
2020-10-29 16:07:25,598 ERROR: Exception on /edit_profile [POST] [in /home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/marc/programming/sqlalchemy_app/app/routes.py", line 57, in edit_profile
    if form.validate():
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/form.py", line 150, in validate
    if not field.validate(self, extra):
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "/home/marc/programming/sqlalchemy_app/app/forms.py", line 23, in validate_username
    user = User.query.filter_by(username=self.username.data).first()
NameError: name 'User' is not defined
2020-10-29 16:07:33,060 ERROR: Exception on /edit_profile [POST] [in /home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/marc/programming/sqlalchemy_app/app/routes.py", line 57, in edit_profile
    if form.validate():
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/form.py", line 150, in validate
    if not field.validate(self, extra):
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "/home/marc/programming/sqlalchemy_app/app/forms.py", line 23, in validate_username
    user = User.query.filter_by(username=self.username.data).first()
NameError: name 'User' is not defined
2020-10-29 16:11:41,987 ERROR: Exception on /edit_profile [POST] [in /home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/marc/programming/sqlalchemy_app/app/routes.py", line 57, in edit_profile
    if form.validate():
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/form.py", line 150, in validate
    if not field.validate(self, extra):
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/marc/programming/sqlalchemy_app/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "/home/marc/programming/sqlalchemy_app/app/forms.py", line 23, in validate_username
    user = User.query.filter_by(username=self.username.data).first()
NameError: name 'User' is not defined
2021-03-20 20:54:32,660 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 20:54:51,853 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 20:56:13,814 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 20:56:25,491 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 21:23:52,876 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 21:34:26,025 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 21:35:36,089 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 21:36:24,751 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 21:36:38,906 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 21:37:05,118 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 21:39:09,648 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 21:48:33,666 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-20 21:49:09,884 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-21 14:40:30,151 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-21 16:56:02,140 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
2021-03-21 16:56:12,591 INFO: SQLAlchemy startup [in /home/marc/programming/alchemy_app/app/__init__.py:29
